name: m196stylecommands
version: 1.4
main: src.main.java.com.m196.projects.m196stylecommands
api-version: 1.21
commands:
  dropanvil:
    description: "drop an anvil on a player :)"
    usage: "/dropanvil <player>"
  adminstick:
    description: "obtain a stick that does 10,000 damage"
    usage: "/adminstick"
  nm:
    description: "obtain 'nutritional mace' that is actually very healthy, while also dealing damage"
    usage: "/nm"