name: m196stylecommands
version: 1.0-alpha
main: com.m196.projects
api-version: 1.21
commands:
  dropanvil:
    description: "drop an anvil on a player :)"
    usage: "/dropanvil <player>"
  adminwand:
    description: "give a player an admin wand"
    usage: "/adminwand"