name: m196stylecommands
version: 1.3-beta
main: src.main.java.com.m196.projects.m196stylecommands
api-version: 1.21
commands:
  dropanvil:
    description: "drop an anvil on a player :)"
    usage: "/dropanvil <player>"